name: build-zip

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          git archive --format=zip --output glcbc-portal.zip HEAD
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glcbc-portal
          path: glcbc-portal.zip
